import { Page } from "page.slint";
import { Item } from "item.slint";
import { RustBackend, AppState, LoadStatus } from "global.slint";
import { Button , ProgressIndicator, VerticalBox, LineEdit, Switch, TextEdit} from "std-widgets.slint";
import { StatusBox } from "status_box.slint";

export component ConfigurationPage inherits Page {  
    title: "Configuration";
    Item {
        title: "Path";
        VerticalBox {
            padding: 10px;
            path_field := TextInput  { 
                horizontal-alignment: TextHorizontalAlignment.center;
                vertical-alignment: TextVerticalAlignment.center;
                font-size: 35px;
                read-only: true; 
                text: AppState.conf-path; 
            }
        }
    }
    Button {
        text: "Reload";
        clicked => {
            RustBackend.loading-configuration();
        }
    }
    StatusBox { 
        title: "Status"; 
        msg: AppState.configuration-status-msg; 
        status: AppState.configuration; 
    }   

}
