import { Page } from "page.slint";
import { Item } from "item.slint";
import { RustBackend, AppState, LoadStatus } from "global.slint";
import { Button , ProgressIndicator, VerticalBox} from "std-widgets.slint";

export component ListingPage inherits Page {
    Item {
        title: "Ldap users";
        VerticalBox  {
            Button { 
                text: "List ldap users"; 
                clicked => {
                    RustBackend.listing-ldap-users()
                } 
            }
            ProgressIndicator { 
                visible:  AppState.is-listing-ldap-user == LoadStatus.Loading; 
                indeterminate: AppState.is-listing-ldap-user == LoadStatus.Loading; 
            }
        }
    }
}
