import { Page } from "page.slint";
import { Item } from "item.slint";
import { RustBackend, AppState, LoadStatus, TableForListing } from "global.slint";
import { Button , ProgressIndicator, VerticalBox, StandardTableView, ScrollView, HorizontalBox, GroupBox} from "std-widgets.slint";
import { EntryField } from "entry_field.slint";
import { StatusBox } from "status_box.slint";


export component ListingPage inherits Page {
    
    Item {
        title: "Ldap readonly login";
        VerticalBox {
            EntryField { 
                input-text: ""; 
                label-text: "Username";  
                placehodler-text: "Username of readonly LDAP user.";
            }
            EntryField { 
                input-text: ""; 
                label-text: "Password"; 
                placehodler-text: "Password to log in as readonly LDAP user.";
                as-password: true;
            }
        }
    }
    Item {
        title: "Ldap users";
        VerticalBox  {
            vertical-stretch: 1;
            Button { 
                text: "List ldap users"; 
                clicked => {
                    RustBackend.listing-ldap-users()
                } 
            }
            ProgressIndicator { 
                visible:  AppState.is-listing-ldap-user == LoadStatus.Loading; 
                indeterminate: AppState.is-listing-ldap-user == LoadStatus.Loading; 
            }
            StatusBox { 
                msg: AppState.listing-ldap-msg; 
                status: AppState.is-listing-ldap-user; 
            }
            GroupBox  {
                title: "Table";
                    StandardTableView { 
                        vertical-stretch: 1;
                        columns: AppState.table-ldap-users.headers;
                        rows: AppState.table-ldap-users.columns;
                    }   

            }
            
            
        }
    }
}
