
import { VerticalBox } from "std-widgets.slint";

export component Page inherits VerticalBox { 
    in property<string> title: "title";

    Text {
       height: 30px;
       font-size: 20px;
       horizontal-alignment: TextHorizontalAlignment.center;
       text <=> root.title;
    }
    Rectangle {
        border-width: 3px;
        border-radius: 3px;
        height: 10px;
        background: #4f4e5e;
    }
    @children
}
