name: Check

on:
  push:
    branches: 
      - main
    paths-ignore:
      - '**/*.md'
      - 'docker/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - 'docker/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository content"
        uses: actions/checkout@v3
        
      - name: "Install needed rust toolchain stable"
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy, rustfmt
            
      - name: "Check formatting"
        run: cargo fmt --check --all
          
      # - name: "Building project to see if it compiles and does not produce any warnings" 
      #   run: cargo clippy --all -- -Dwarnings
      
      - name: "Check linting" 
        run: cargo clippy --all
        
      - name: "Run unit tests" 
        run: cargo test --workspace --verbose
          
